apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-booc
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2 #Change
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 50Mi #Change
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0 #Change
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5  #Change
    scaleUp:
      stabilizationWindowSeconds: 0 #Change
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5  #Change