apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers: 
      - name: backend-app
        image: BoocApp.azurecr.io/backend-app:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "6400"
        resources:
          requests:
            cpu: 128m
            memory: 128Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    app: backend-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6400