#This handles the tls secrets for the https ingress termination
apiVersion: v1
kind: Secret
metadata:
  name: backend-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    ${{ secrets.CERTIFICATE }}
  tls.key: |
    ${{ secrets.CERT_KEY }}