#This handles the tls secrets for the https ingress termination
apiVersion: v1
kind: Secret
metadata:
  name: backend-tls
type: kubernetes.io/tls
data:
  server.crt: $CERTIFICATE
  server.key: $CERT_KEY